# Generated by Django 4.0 on 2024-04-04 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0003_auto_20240327_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='students_applied_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_date', models.DateField()),
                ('attendance', models.CharField(max_length=100)),
                ('placed_status', models.CharField(max_length=100)),
                ('shortlisted_status', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('field1', models.CharField(blank=True, max_length=100, null=True)),
                ('field2', models.CharField(blank=True, max_length=100, null=True)),
                ('field3', models.CharField(blank=True, max_length=100, null=True)),
                ('applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.job')),
                ('applied_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.student')),
            ],
            options={
                'db_table': 'students_applied_details',
            },
        ),
    ]
