# Generated by Django 4.0 on 2024-04-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0004_students_applied_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_applied_details',
            name='attendance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students_applied_details',
            name='placed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students_applied_details',
            name='placed_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students_applied_details',
            name='shortlisted_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
