# Generated by Django 4.0 on 2024-04-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0005_alter_students_applied_details_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tpc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tpc',
            },
        ),
    ]
